---
kind: pipeline
name: linux-amd64
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/hardened-build-base:v1.16.6b7
  volumes:
    - name: docker
      path: /var/run/docker.sock
  commands:
    - make image-build

- name: scan
  image: rancher/hardened-build-base:v1.16.6b7
  volumes:
    - name: docker
      path: /var/run/docker.sock
  commands:
    - TAG=${DRONE_TAG} make image-scan
  when:
    event:
      - tag
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
      - refs/tags/*

- name: publish
  image: rancher/hardened-build-base:v1.16.6b7
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make DRONE_TAG=${DRONE_TAG} image-push image-manifest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
      - tag
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
      - refs/tags/*

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
