---
kind: pipeline
name: linux-amd64
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/hardened-build-base:v1.16.4b7
  volumes:
    - name: docker
      path: /var/run/docker.sock
  commands:
    - make image-build
  when:
    event:
      - push
      - pull_request

- name: docker-build
  image: plugins/docker
  environment:
    TAG: ${DRONE_TAG}
  settings:
    purge: false
    custom_dns: 1.1.1.1
    tag: ${DRONE_TAG}-linux-amd64
    password:
      from_secret: docker_password
    repo: rancher/hardened-kubernetes
    username:
      from_secret: docker_username
    build_args_from_env-args:
      - TAG
  when:
    event:
      - tag
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
      - refs/tags/*

- name: scan
  image: rancher/hardened-build-base:v1.16.4b7
  volumes:
    - name: docker
      path: /var/run/docker.sock
  commands:
    - TAG=${DRONE_TAG} make image-scan
  when:
    event:
      - tag
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
      - refs/tags/*

- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  when:
    event:
      - tag
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
      - refs/tags/*

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
